openapi: 3.0.3
info:
  title: Async Task API
  version: 1.0.0
servers:
  - url: /api/v1

paths:
  /tasks:
    post:
      tags:
          - tasks
      summary: Создать новую задачу
      operationId: CreateTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
      responses:
        '202':
          description: Принято в обработку
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Неверный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /tasks/{id}:
    get:
      tags:
          - tasks
      summary: Получить статус/результат задачи
      operationId: GetTask
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Текущий статус и результат
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Задача не найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
        status:
          type: string
          enum: [pending, running, done, failed]
        result:
          type: object
          nullable: true
        error:
          type: string
          nullable: true
        createdAt:
          type: string
          format: date-time

    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
